name: DEBUG STRUCTURE

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SHOW STRUCTURE
        run: |
          echo "PWD:"
          pwd
          echo "------------------"
          echo "ROOT LS:"
          ls -la
          echo "------------------"
          echo "TREE:"
          find . -maxdepth 4 -type f
