name: Africa Grants Bot (Test)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restore bot state cache
        uses: actions/cache@v4
        with:
          path: .state
          key: bot-state-v1

      - name: Install dependencies
        working-directory: .
        run: |
          echo "=== FILES IN WORKDIR ==="
          ls -la
          echo "========================"
          pip install -r requirements.txt

      - name: Run bot
        working-directory: .
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python main.py

      - name: Save bot state cache
        uses: actions/cache@v4
        with:
          path: .state
          key: bot-state-v1